Repository Caphyon/rc-strings, pull requests merged in 2018-08, with the labels that each got.

#30 Dispay rc name on edit command
  NewSrc/RcStrings.VsPackage/CommonControlsStyles.xaml
  NewSrc/RcStrings.VsPackage/EditStringResourceDialog.xaml
Labels: bug

#40 Main header(Resource.h) detection is not case-insensitive
  NewSrc/RcStrings.VsPackage/StringResourceContext.cs
Labels: bug

#42 Improve value formatting
  NewSrc/RcStrings.VsPackage/RcStrings.VsPackage.csproj
  NewSrc/RcStrings.VsPackage/RcStringsPackage.cs
  NewSrc/RcStrings.VsPackage/SelectionFormatter.cs
  NewSrc/RcStrings.VsPackage/ValidatorsUi/ErrorCollector.cs
  NewSrc/RcStrings.VsPackage/ValidatorsUi/IdValidatorUi.cs
  NewSrc/RcStrings.VsPackage/ValidatorsUi/NameValidatorUi.cs
  NewSrc/RcStrings.VsPackage/ValidatorsUi/UiConstants.cs
  NewSrc/RcStrings.VsPackage/ValidatorsUi/ValueValidatorUi.cs
Labels: enhancement

#43 Fix name possibly being null after parsing RC
  NewSrc/StringEnhancer/StringEnhancer/RC File/RCFileParser.cs
Labels: bug

#44 Fix crash when words split return empty
  NewSrc/StringEnhancer/StringEnhancer/RC File/RCFileParser.cs
Labels: bug

#45 Rename "RC Strings Page" to "General"
  NewSrc/RcStrings.VsPackage/RcStringsPackage.cs
Labels: refactor

#48 Improve main resource header file detection
  NewSrc/RcStrings.VsPackage/StringResourceContext.cs
Labels: bug

#50 Fix crash when parsing empty or invalid lines in RC
  NewSrc/StringEnhancer/StringEnhancer/RC File/RCFileParser.cs
Labels: bug

#49 Release v1.4.0
  CHANGELOG.md
  NewSrc/RcStrings.VsPackage/source.extension.vsixmanifest
Labels: release

#51 Add support for editing names
  NewSrc/RcStrings.VsPackage/EditStringResourceDialog.xaml
  NewSrc/RcStrings.VsPackage/EditStringResourceDialog.xaml.cs
  NewSrc/RcStrings.VsPackage/RcStringsPackage.cs
  NewSrc/RcStrings.VsPackage/StringResourceContext.cs
  NewSrc/RcStrings.VsPackage/ValidatorsUi/ErrorCollector.cs
  NewSrc/StringEnhancer/StringEnhancer/Header File/HeaderWriter.cs
  NewSrc/StringEnhancer/StringEnhancer/Helpers/HeaderNamesExtractor.cs
  NewSrc/StringEnhancer/StringEnhancer/LineParser.cs
  NewSrc/StringEnhancer/StringEnhancer/RC File/RCFileWriter.cs
Labels: enhancement

#52 Show disabled rcs in combobox
  NewSrc/RcStrings.VsPackage/CommonControlsStyles.xaml
  NewSrc/RcStrings.VsPackage/EditStringResourceDialog.xaml
  NewSrc/RcStrings.VsPackage/RcFile.cs
  NewSrc/RcStrings.VsPackage/RcStrings.VsPackage.csproj
  NewSrc/RcStrings.VsPackage/RcStringsPackage.cs
  NewSrc/RcStrings.VsPackage/Resources/CheckedIcon.png
  NewSrc/RcStrings.VsPackage/Resources/InvalidIcon.png
Labels: enhancement

#53 Fix error when editing invalid rc
  NewSrc/RcStrings.VsPackage/RcStringsPackage.cs
  NewSrc/RcStrings.VsPackage/StringResourceContext.cs
Labels: bug

#56 Disable done button for invalid input
  NewSrc/RcStrings.VsPackage/CommonControlsStyles.xaml
  NewSrc/RcStrings.VsPackage/EditStringResourceDialog.xaml
  NewSrc/RcStrings.VsPackage/EditStringResourceDialog.xaml.cs
  NewSrc/RcStrings.VsPackage/InverseBooleanConverter.cs
  NewSrc/RcStrings.VsPackage/RcStrings.VsPackage.csproj
Labels: enhancement

#57 Update manifest version
  CHANGELOG.md
  NewSrc/RcStrings.VsPackage/source.extension.vsixmanifest
Labels: release

#58 Create settings button
  NewSrc/RcStrings.VsPackage/EditStringResourceDialog.xaml
  NewSrc/RcStrings.VsPackage/EditStringResourceDialog.xaml.cs
  NewSrc/RcStrings.VsPackage/RcStrings.VsPackage.csproj
  NewSrc/RcStrings.VsPackage/RcStringsPackage.cs
  NewSrc/RcStrings.VsPackage/Resources/gear-settings (1).png
  NewSrc/RcStrings.VsPackage/Resources/gear-settings2.png
  NewSrc/RcStrings.VsPackage/Resources/options.png
  NewSrc/RcStrings.VsPackage/Resources/settings.png
Labels: enhancement

#59 catch all the exceptions form the add command
  NewSrc/RcStrings.VsPackage/RcStringsPackage.cs
Labels: bug

#60 remove Lightweight Solution Load support
  NewSrc/RcStrings.VsPackage/RcStrings.VsPackage.csproj
  NewSrc/RcStrings.VsPackage/RcStringsPackage.cs
  NewSrc/RcStrings.VsPackage/Vs15SolutionLoader.cs
Labels: bug
